name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            exe_suffix: '.exe'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        name: rc4md5cry${{ matrix.exe_suffix }}
        path: target/release/rc4md5cry${{ matrix.exe_suffix }}
